### ISSUE TITLE
Laod custom LC0 network error

### ISSUE THREAD

**Issue by al75an** [hxim/PeshkaChess#2]
Hi,
Thank you for this awesome chess GUI.
Could you please help to fix the issue
the gui fails to use the custom lc0 (error incorrect header check )
I tried more than 10 different lc0 networks
Any help would be greatly appreciated

**Comment by hxim** [comment]
Hi,
I am sorry. I did not write code for lc0 network backend myself it was taken from this project here https://github.com/frpays/lc0-js but it seems to be not updated and works only for 30xxx or older lc0 networks unfortunately.

**Comment by al75an** [comment]
thank you for letting me know,
could you please fix this in the future updates
may God bless you and bless your work
